### ISSUE TITLE
Update public roadmap of project 

### ISSUE THREAD

**Issue by adrianLIrobotics** [5G-ERA/middleware#100]
**Is your feature request related to a problem? Please describe.**
Currently we have in the main git page a public roadmap. It should be updated every month (with agreed features of team members) and maybe also updated in the main web page. Contact EBos for this one. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/26432703/212562790-867efcfb-f79c-40a1-9b51-de75d5533066.png)

**Comment by Artonus** [comment]
The public roadmap of the documentation should be adjusted to the current state of the release planning to give a very general overview of what is currently conducted in the development of the 5G-ERA Middleware

**Comment by diwalipathak** [comment]
done !
