### ISSUE TITLE
Working policies implementation required

### ISSUE THREAD

**Issue by adrianLIrobotics** [5G-ERA/middleware#124]
**Is your feature request related to a problem? Please describe.**

Implement, design and validate all middleware policies.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Artonus** [comment]
We will have to consider not only global policies but also scoped policies. During the meeting, we identified the example "Deployment Policy" that will allow the deployment of the specific NetApp only in the private Cloud/Edge machine, not the public one.

**Comment by Artonus** [comment]
The initial policy in the system will be the Network Slice Selection Policy. This is needed as part of the Slice Manager integration into the Middleware. 
The policy can be attached to the `Instance` and specify what actions must be considered when deploying the `Instance`.  
The example `Policy` _URLLC Network_ would mean that if the Slicing mechanism is available, connect the `Robot` utilising the instance to the URLLC Network Slice.

Things to be compleated:
* [ ] Division of the `Policies` into the system-scoped and Instance-scoped
* [ ] How to attach policies to the Instance / another object like `Robot`.
* [ ] Implementation of the URLLC `Policy`.
