### ISSUE TITLE
AC/AS integration with network application client ROS wrapper limitations

### ISSUE THREAD

**Issue by adrianLIrobotics** [5G-ERA/middleware#140]
AS/AC ROS integration with network application Client

To translate the json response from the network application in the network client back to ROS , there is a need to create a ROS grapper that is universal. Solution may be to use ROS bridge suite to translate all json back to ROS. It needs research and testing.

**Comment by Artonus** [comment]
@adrianLIrobotics, isn't it handled by the RelayNetApp?
