### ISSUE TITLE
Infrastructure as code - automated infrastructure deployment

### ISSUE THREAD

**Issue by radu-popescu** [5G-ERA/middleware#145]
**Is your feature request related to a problem? Please describe.**
The need for an automated infrastructure deployment has to be addressed for to purpose of quick recovery in case of potential incidents on the AWS platform.

**Describe the solution you'd like**
Terraform infrastructure as code

**Describe alternatives you've considered**
AWS Cloud Formation, Ansible 

**Additional context**
This has to be implemented as soon as possible, it is a high priority task.

**Comment by Artonus** [comment]
@radu-popescu we already have an issue created for this -  #116. Please add the details over there if necessary, I will close this issue as duplicate.

**Comment by radu-popescu** [comment]
My bad, I haven't seen that we already had one open.

**Comment by Artonus** [comment]
No problem :)
