### ISSUE TITLE
Semantic map: translation from ROS 1 to ROS 2

### ISSUE THREAD

**Issue by adrianLIrobotics** [5G-ERA/middleware#166]
Rewrite the code with the 3 ros nodes into ROS 2.

**Comment by adrianLIrobotics** [comment]
@Yujiezhao0 

https://github.com/5G-ERA/signal_quality_network_application

Code to be translated in ros 2.

**Comment by Artonus** [comment]
Done by @adrianLIrobotics during the integration meeting in Athens
