### ISSUE TITLE
Dashboard endpoints

### ISSUE THREAD

**Issue by Artonus** [5G-ERA/middleware#48]
The dashboard endpoints will cover extracting specific data from the Middleware APIs.

1. The endpoint has to present information about the cloud and the edges they're currently operating in the system.
The endpoint has to return the following properties:

    Last Time the location updated
    Name of the Edge/Cloud
    Is it online
    Is it busy
    Number of containers it runs
    status of a cloud/edge

2. The endpoint has to present information about the robots and the tasks that they're currently executing.
The endpoint has to return the following properties:

 *   Robot name/id
 *   Task name/id
 *   Date and Time it started
 *   Status of a task
 *   The date and Time finished
 *   status of a robot

Dashboard integration proposal [document](https://docs.google.com/document/d/1izXGbP7aVGNBEQuAwO4XehJlaUVHfrMFfML3-pQjlWY/edit) 

Git branch for feature: [Redis interface dashboard/157](https://github.com/5G-ERA/middleware/pull/43)

**Comment by adrianLIrobotics** [comment]
Edited issue and added link to Dashboard proposal for feature tracking.

**Comment by adrianLIrobotics** [comment]
I will continue the extra endpoints as agreed.

**Comment by adrianLIrobotics** [comment]
Added Basic cascading grid for action sequence endpoint for dashboard.

**Comment by adrianLIrobotics** [comment]
Added missing endpoints, only needs QA testing

**Comment by adrianLIrobotics** [comment]
issue #93 and #94 still under progress
