### ISSUE TITLE
Central Topology API definition and implementation

### ISSUE THREAD

**Issue by adrianLIrobotics** [5G-ERA/middleware#51]
**Is your feature request related to a problem? Please describe.**
There is no data for the dashboard about the status of edge/cloud defined in Redis or how to capture it.

**Describe the solution you'd like**
For the multiple Middleware instances deployed in the topology, there is a necessity for each of the Middleware to report the status of the platform they are running on (edge/cloud). The status should be online, CPU usage, disk space etc. This is necessary for the dashboard and resource planner.
On top of this, the ActionServer/Client in the Robot could query for all the possible locations of the Middleware through the Central TopologyAPI. The Robot could decide by itself which Middleware location suits it the best.

**Comment by Artonus** [comment]
![MiddlewareCooperationConcept excalidraw](https://user-images.githubusercontent.com/34897359/207090250-6c524791-7a13-4d02-bbdd-7985861e39d8.png)
Added the proposed schema of the topology
