### ISSUE TITLE
Integration of new netApp design with middleware and AS/AC

### ISSUE THREAD

**Issue by adrianLIrobotics** [5G-ERA/middleware#54]
**Describe the solution you'd like**
The new NetApp design requires the endpoint for planning in Middleware to pass the ROS topics and topics types. This is necessary for querying suitable NetApps based on the required input topics. This interface to the NetApp must be loaded in the Redis DB index of netApp as extra information that must be included.
Additionally, the AC/AS needs to be expanded to include in the ROS goal the topics of the robot. AS will be integrated with the NetApp client. 

BB 27.02.2023 - ~~based on the conversation with @Kapim the following adjustments to the Middleware must be made:
During the deployment, the Middleware has to assign a randomised port in the specified range that will not conflict with the existing NetApps (port range 49152-65535). On top of this, the range of ports (which does not have to be sequential) has to be assigned for the NetApp to utilise the Gstreamer~~.

This idea has changed during the development of the Relay and Inter-Relay NetApps.

**Comment by Artonus** [comment]
What needs to be discussed is the automatic gateway reconfiguration #134. It will allow for the redirection of the GStreamer traffic directly to the NetApp through a unified access point.

**Comment by Artonus** [comment]
Blocked by #134 and #158

**Comment by Artonus** [comment]
AC/AS needs to embed the Network Application client for it to handle the connection to the Middleware. On top of this, the AC/AS will serve it's own designed purposes of keeping the interaction between robot and the Middleware

**Comment by Artonus** [comment]
This issue is out of date. Now we natively support ROS1 and ROS2 applications.
