### ISSUE TITLE
Bash script for Onboarding robot

### ISSUE THREAD

**Issue by adrianLIrobotics** [5G-ERA/middleware#55]
**Is your feature request related to a problem? Please describe.**
Help the user to automatically load into the middleware database the robot ROS information.

**Describe the solution you'd like**
The bash script will be run in the robot Linux system and partially complete the onboarding file for the robot. The information completed will be ROS info and basic OS and system architecture.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by adrianLIrobotics** [comment]
Python version: 
https://github.com/5G-ERA/middleware/blob/main/util/onboarding_robot.py

**Comment by Artonus** [comment]
done
