### ISSUE TITLE
⚠️Feedback of ROS action server instance is colliding.

### ISSUE THREAD

**Issue by adrianLIrobotics** [5G-ERA/middleware#56]
**Describe the bug**
The feedback in action server netApp instance goes up and down very fast.

**To Reproduce**
Steps to reproduce the behavior i.e.:
Run the BUT image recognition netApp deployed by middleware with AC/AS and look at the output of AS in console.

**Expected behavior**
The feedback is either up or down and does not change every second.

**Screenshots**

**Additional context**
This was first reported by RobotNik in the septeber 2022 integration.

**Comment by Artonus** [comment]
Blocked by #71

**Comment by Artonus** [comment]
CLosed as part of #115
