### ISSUE TITLE
⚠️ Middleware - Architecture documentation

### ISSUE THREAD

**Issue by Artonus** [5G-ERA/middleware#57]
Middleware lacks the full architecture documentation. To enable getting familiar with the Middleware's architecture quicker, prepare the document that will present the following things:

- Possible Middleware deployment scenario
- How the Middleware services contact each other
- Management process (Onboarding) of the NetApps (reference netApp onboarding)
- Diagrams showcasing the Architecture (Including CentralApi)

**Comment by diwalipathak** [comment]
Do you need any architecture diagrams atall from 4.1 ? or everything here will be new and from start
