### ISSUE TITLE
Task GUIDs needs to be descriptive and not a random number

### ISSUE THREAD

**Issue by adrianLIrobotics** [5G-ERA/middleware#58]
**Describe the bug**
For ROS developer it is very difficult to remember what the task GUID is about by looking at the GUID. It should be a task name and will be descriptive.

It must be integrated with the middleware correctly and with the Redis database.

**Additional context**
Reported on RobotNik september intgration 2022.

**Comment by Artonus** [comment]
As talked through with Michal, the Robot will call the Action Client with two possible requests:

1. Direct call for a single NetApp, robot will specify what task it wants to conduct
2. Semantic planning call, the robot will call the Middleware with the request to prepare the high-level task and the resources needed to conduct the task.

**Comment by adrianLIrobotics** [comment]
Isnt this issue duplicate #79 ?

**Comment by adrianLIrobotics** [comment]
closing as duplicate
