### ISSUE TITLE
📝 🖍Resource Replanning documentation

### ISSUE THREAD

**Issue by diwalipathak** [5G-ERA/middleware#60]
**Is your feature request related to a problem? Please describe.**
This documentation will include the step-by-step flowchart of replanning resources for resource planner to complete a task_1.

**Describe the solution you'd like**
I am currently working on it. 

![Replanning simple scenario](https://user-images.githubusercontent.com/93341077/205023525-c85550d9-4d1c-407f-8f51-9835f8993356.png)

**Comment by diwalipathak** [comment]
Updated Resource Replanning documentation

**Comment by adrianLIrobotics** [comment]
Change this to the column work in progress if you are currently working on it :)

**Comment by diwalipathak** [comment]
https://docs.google.com/document/d/1k0_1qmFeIuiEUV18Xjz90AjMdgGMJhoSb264me3EPaY/edit#
