### ISSUE TITLE
⚠️Fix stage 3 of BED 2022 Workshop

### ISSUE THREAD

**Issue by adrianLIrobotics** [5G-ERA/middleware#62]
**Describe the bug**
Stage 3 does not work. Container with webots simulation is working but not with ROS.
The problem seems to be the k8 is deploying an updated version of webots that is not compatible with the ROS Simulation. Fix should be to change tag lastest from deployment.yaml to the specific version working in march 2022. 

**To Reproduce**
Steps to reproduce the behavior i.e.:
[Follow](https://github.com/5G-ERA/BED-Workshop)

**Expected behavior**
ROS Webots simulation runs fine

**Screenshots**
N/A

**Additional context**
N/A

**Comment by diwalipathak** [comment]
![ROS-SIMULATION](https://user-images.githubusercontent.com/93341077/205026413-9d0e14c1-cca3-4876-bbdb-ce2c694a04b1.jpg)
Screenshot attached
