### ISSUE TITLE
Security roles for the middleware and robot

### ISSUE THREAD

**Issue by adrianLIrobotics** [5G-ERA/middleware#66]
**Is your feature request related to a problem? Please describe.**
The dashboard requires different permissions based on roles to delete redis relationships, modify policies etc.

**Describe the solution you'd like**
Admin role and simple user role needed. Also, the robot is below the system admin. Show if a policy set by system admin collides with a robot reject, the policy from system admin prevails. 

Modify registration and login endpoints accordingly.

**Comment by adrianLIrobotics** [comment]
Consider thrid party provider:
https://auth0.com/

**Comment by Artonus** [comment]
This is a duplicate.
