### ISSUE TITLE
Middleware integration with 5G Testbed proposal

### ISSUE THREAD

**Issue by Artonus** [5G-ERA/middleware#78]
**Is your feature request related to a problem? Please describe.**
The ways of how the Middleware will communicate with the testbed. For this, we have to know the following:
* What are the capabilities of the testbed and OSM as Slice Orchestrator? 
* What exactly is a Slice?
* How the Middleware has to request a new slice?
* Does create a new slice change the IP addresses of the Middleware?

The desired way of communicating from the Robot to the slice request is the following:
ROS  ->  Middleware (including AC/AS) -> Orchestrator (OSM)-> slice-manager (testbed) ->websocket (NetApp)

**Comment by adrianLIrobotics** [comment]
[5gSlicing.docx](https://github.com/5G-ERA/middleware/files/10238343/5gSlicing.docx)

Added notes from confrence with 5g partners

**Comment by Artonus** [comment]
As a part of the SliceManager implementation, we will need to think about how we will store the information that some `Edge` or `Cloud` has access to the Network Slices.

**Comment by Artonus** [comment]
To be compleated:
- [ ] Connection and communication with the Slice Manager API
- [ ] Storing globally (in redis) the information about the slicing mechanism available at some locations with the types of Slices available
