### ISSUE TITLE
Define the testing template and testing environment

### ISSUE THREAD

**Issue by Artonus** [5G-ERA/middleware#80]
The testing templates should be defined and distributed across the team. In addition, the testing scenarios should be prepared for the testing of the Issues and QA. 

The testing templates will be used not only by the QA but also by the team itself to initially test the produced features.

**Comment by adrianLIrobotics** [comment]
- [ ] Check University VPN for accesing testing scenario.

**Comment by diwalipathak** [comment]
Test template ; 
Tester name 
Test date
Feature tested 
Project/test cycle
test platform
device/browser 
test purpose
[Test-Template.xlsx](https://github.com/5G-ERA/middleware/files/10286152/Test-Template.xlsx)

**Comment by adrianLIrobotics** [comment]
How are we doing with the testing enviroment? VPN needs to be provided.
