### ISSUE TITLE
Redis Cluster deployment

### ISSUE THREAD

**Issue by Artonus** [5G-ERA/middleware#85]
The Redis Cluster will allow the Middleware to decrease the time it takes the Middleware to fetch the data.
The cluster replica should be placed in each Middleware location. It will be especially important with the Middleware working as a distributed system as part of #68. 

On top of this, the Redis Cluster should be able to easily facilitate the new replica that could be deployed automatically with the Middleware. More thought will have to be placed into this, as this will be a critical point for Middleware in terms of accessing the planning resources.

**Comment by radu-popescu** [comment]
The cluster has been successfully deployed using the redis-stack-server image.
Requires, testing of the replication, persistence and pod failure.

**Comment by radu-popescu** [comment]
All tests have passed.
