### ISSUE TITLE
⚠️ CheckInstanceByRobotRosDistro in ActionPlanner does not work

### ISSUE THREAD

**Issue by adrianLIrobotics** [5G-ERA/middleware#95]
**Describe the bug**
The service model inside the actionModel input parameter to the function has null value. 

**To Reproduce**
Steps to reproduce the behavior i.e.:
branch: AL/SimplifiedResourceDeployment (based on Main)

0. Launch docker-compose 
1. Go to postman
2. endpoint: http://localhost:5047/task/plan?dryRun=true)
3. body: 

{
    "RobotId": "967eb8c1-3078-4210-8312-af1f8187d2c8",
    "resourceReusage": false,
    "ReplanActionPlannerLocked": false,
    "TaskId": "a9fdafe6-9b90-48bc-a286-3f08ed0a78aa",
    "TaskDescription": "",
    "ContextKnown": true,
    "Questions":
    [
    {
      "relations": [
        {
          "initiatesFrom": {
            "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "type": "string",
            "name": "string"
          },
          "relationName": "string",
          "relationAttributes": [
            {
              "key": "string",
              "value": "string"
            }
          ],
          "pointsTo": {
            "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "type": "string",
            "name": "streing"
          }
        }
      ],
      "Id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "Question": "string",
      "IsSingleAnswer": true,
      "Answer": [
        {
          "key": "string",
          "value": "string"
        }
      ]
    }
  ] 
}

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/26432703/211334020-812befd2-5e3b-448b-929b-d2eb61e74cb2.png)

**Additional context**

I think this error may be caused for not addapting the code to the lastest fix of object mapping between containers.

**Comment by Artonus** [comment]
@adrianLIrobotics I believe that this is caused by the same situation I have described in #93
