### ISSUE TITLE
Prepare onboarding templates of edges, cloud, instance for dashboard

### ISSUE THREAD

**Issue by adrianLIrobotics** [5G-ERA/middleware#97]
The dashboard interface has a button that can be used to download the onboarding templates for entities in middleware. This template is completed by dashboard user and can be uploaded to the dashboard to create a new entity in middleware.

**Comment by Artonus** [comment]
We have to simplify the models for passing and retrieving the data. 
At the moment the models have unnecessary p[properties like Relations and other values that should not be specified by the end user.

This will be a breaking change when it comes to the Dashboard, so the partners will have to be informed accordingly.

For release v0.2, we have to prepare the model structure about which we will inform partners. The Implementation of the new models will be scheduled for release v0.3.

**Comment by Artonus** [comment]
@adrianLIrobotics prepared the onboarding templates. Now, for the v0.3, it is time to prepare and document changes and let partners know their handling process

**Comment by Artonus** [comment]
On top of this, I suggest adding model validation when requests are made. 
The package that will help this is https://docs.fluentvalidation.net/en/latest/index.html
